version : '3.4'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: creditdb
    networks:
      - db-network
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql/init:/docker-entrypoint-initdb.d/:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mysql_view
    #network_mode: host
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8090:80
      
  # credit:
    # build: ./credit
    # #network_mode: host
    # container_name: credit
    # networks:
      # - db-network
    # depends_on:
      # - mysql
    # # links:
      # # - phpmyadmin
    # restart: on-failure
    # ports:
      # - 8080:8080

  # product:
    # build: ./product
    # #network_mode: host
    # container_name: product
    # networks:
      # - db-network
    # depends_on:
      # - mysql
    # # links:
      # # - credit
    # restart: on-failure
    # ports:
      # - 8082:8082
      
  # customer:
    # build: ./customer
    # #network_mode: host
    # container_name: customer
    # networks:
      # - db-network
    # depends_on:
      # - mysql
    # # links:
      # # - credit
    # restart: on-failure
    # ports:
      # - 8081:8081

networks:
  db-network:
    driver: bridge
      
