version : '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: creditdb
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql/init:/docker-entrypoint-initdb.d/:ro
    # networks:
      # - fullstack

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mysql_view
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8090:80
      
  # credit:
    # build: ./credit
    # container_name: credit
   # # links:
     # # - mysql
   # # restart: always
    # ports:
      # - 8080:8080
    # networks:
      # - fullstack

  # product:
    # build: ./product
    # container_name: product
   # # links:
     # # - mysql
   # # restart: always
    # ports:
      # - 8081:8081
    # networks:
      # - fullstack
      
  # customer:
    # build: ./customer
    # container_name: customer
   # # links:
     # # - mysql
   # # restart: always
    # ports:
      # - 8082:8082
    # networks:
      # - fullstack
      
# networks:
    # fullstack:
        # driver: bridge
      
